### ISSUE TITLE
"Compiled" version?

### ISSUE THREAD

**Issue by circuitfry** [nuclearace/CytubeBot#52]
Gah, I'm not the best at understanding this stuff very well. Is there by any chance a "pre-compiled" version of this? I'm having trouble finding Visual Studio 2005 and .NET 2.0 SDK won't install.

**Comment by nuclearace** [comment]
I wouldn't even bother trying to get it work on Windows. And no, there's no "pre-compiled" version, since it never gets compiled into an executable.
