### ISSUE TITLE
Upgrade to socket.io-client 2.0

### ISSUE THREAD

**Issue by calzoneman** [nuclearace/CytubeBot#56]
CyTube is upgrading to socket.io 2.0 soon.  CytubeBot should probably be upgraded as well to avoid any strange behavior brought about by version incompatibility.

**Comment by calzoneman** [comment]
Tested this on beta.synchtube.me and it seems to work:

```diff
diff --git a/package.json b/package.json
index eda3447..f412434 100644
--- a/package.json
+++ b/package.json
@@ -6,7 +6,7 @@
   },
   "dependencies": {
     "async": "~0.9.0",
-    "socket.io-client": "^1.3.5",
+    "socket.io-client": "^2.0.3",
     "libxmljs": "~0.18.0",
     "sqlite3": "3.1.8",
     "google-translate-api": "teamsteamdev/google-translate-api",
```
![2017-07-10-205153_415x365_scrot](https://user-images.githubusercontent.com/385672/28050298-cb514ca0-65b1-11e7-8136-88effada8318.png)

**Comment by nuclearace** [comment]
Yeah 2.0 wasn't that big of a change.
