### ISSUE TITLE
Is there a tutorial for noobs?

### ISSUE THREAD

**Issue by antonpictures** [nuclearace/CytubeBot#58]
I paypal-ed to the Xaetai contributor $100 to install cytube on my AWS account with few modifications. After a basic install, the dude go corona, I don't know, he dissapeared with the money and everything. Left me with the unfinished http://3reo.com that has the empty main page instead of looking like in the photo. How do I even access the console to install this chat bot? I need to populate bots so the channels and the screen are both on the same page so i can easly change the channels .  Is there an easy to follow tutorial?
main page: https://i.imgur.com/q8cQy7g.jpg
- admin page: https://i.imgur.com/hbQFtn7.jpg

**Comment by nuclearace** [comment]
Beyond what’s on the readme/code on the cytube readme, I cant really help. You’ll have to try and reach xaekai.

**Comment by nuclearace** [comment]
Have you tried reaching out to the cytu.be owner for help?
